# These settings are only for settings that will not need to be changed while running

modules:
  # Which modules to import and use
  rabbitmq: True
  postgres: True
  # Warning, lots of functionality will fail if not using a postgres database.

  cogs:
    [
      "engfrosh_bot.cogs.cogModeration.moderation",
      "engfrosh_bot.cogs.cogCoin.coin",
      "engfrosh_bot.cogs.cogScav.scav",
      "engfrosh_bot.cogs.cogManagement.management",
    ]

debug: True
log_level: DEBUG

credentials:
  relative_path: credentials.json
  absolute_path: Null
  # If both are provided, will default to the relative path

bot_prefix: "!"

bot_log_channel: [863804486262587423]

guild: 731598642426675301

timezone: America/Toronto

media_root: "files/media"
temp_root: "files/temp"

module_settings:
  rabbitmq:
    host: localhost
    queue: django_discord

  moderation:
    checkmark: True
    reply:
      channel: True
      dm: True

    ignored_channels: [858741004831555634]
    report_channels: [858741004831555634]
    additional_words: ["uottawa"]

    regex_profanity: "[Ff\U0001f1eb]\\s*[uU\U0001f1fa]\\s*[cC\U0001f1e8]\\s*[kK\U0001f1f0]"

    report_message: "{author} sent a message to channel {channel} that broke the moderation rules:\n\n||{content}||"
    profanity_message: "Your message is not appropriate. It has been deleted from the channel and sent to the moderation team."

  coin:
    public_commands: True
    public_confirmations: True
    permission: change_team_coin # Names must be unique as currently written

    scoreboard_channels: [813043254358442034]

    scoreboard:
      header: "Scoin Standings\n=================="
      row: "{place}. {team_name} {coin_amount}"
      # row must contain format placeholders: place, team_name, coin_amount
      name_length: 25
      coin_length: 10

  scav:
    incorrect_message: Null

    settings_names:
      active: "scav_active"

    scoreboard_channels: [883377344419606599]

  management:
    superadmin: [360895010494742529]
    admin: []
    pronouns:
      he: 884035491454930984
      she: 884035547495006258
      they: 884035592537657384
      ask: 884035612208926840

    pronoun_message: [884038532866400276]
    bingo_message: [885689149003272213]
    virtual_team_message: []
