# These settings are only for settings that will not need to be changed while running

modules:
  # Which modules to import and use
  postgres: True
  # Warning, lots of functionality will fail if not using a postgres database.

  cogs: [
    "cogs.cogModeration.moderation",
    "cogs.cogCoin.coin",
    "cogs.cogScav.scav",
    "cogs.cogManagement.management"
    ]

debug: False
log_level: INFO

verify_prefix: 'verification_photos/'

timezone: America/Toronto

module_settings:
  moderation:
    checkmark: True
    reply:
      channel: True
      dm: True

    additional_words: [
      "uottawa"
    ]
    regex_profanity: '$^'

    report_message: "{author} sent a message to channel {channel} that broke the moderation rules:\n\n||{content}||"
    profanity_message: "Your message is not appropriate. It has been deleted from the channel and sent to the moderation team."

  coin:
    public_commands: True
    public_confirmations: True
    permission: change_team_coin # Names must be unique as currently written

    scoreboard:
      header: "Scoin Standings\n=================="
      row: "{place}. {team_name} {coin_amount}"
      # row must contain format placeholders: place, team_name, coin_amount
      name_length: 25
      coin_length: 10

  scav:
    incorrect_message: Null
    user_agent: 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0'

  management:
    superadmin: [264989719312465921]
